image:
  repository: dinesh150/ipl-voter
  tag: "b78f8a4b9acaecd572b3dcdafc9ca0020c3fdcaf"
  pullPolicy: "Always"

replicaCount: 1

service:
  type: NodePort
  port: 80
  targetPort: 5000     
  nodePort: 30007      

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

persistence:
  enabled: true
  size: 100Mi