image:
  repository: dinesh150/ipl-voter
  tag: "c6127682ee0e98011858f12f1dc78cb192e0ae84"
  pullPolicy: "Always"

replicaCount: 1

service:
  type: NodePort
  port: 80
  targetPort: 5000     
  nodePort: 30007      

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

persistence:
  enabled: true
  size: 100Mi